[package]
name = "dpp"
version = "0.1.0"
edition = "2018"
authors = ["Anton Suprunchuk <anton.suprunchuk@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs58 = "0.4.0"
base64 = "0.13.0"
anyhow = { version = "1.0"}
thiserror = { version = "1.0"}
lazy_static = { version ="1.4"}
serde = { version="1.0", features=["derive"]}
dashcore = { git = "https://github.com/dashevo/rust-dashcore", features=["no-std"], default-features = false }
serde_json = { version="1.0"}
ciborium = { version="0.2"}
byteorder = { version="1.4"}
sha2  = { version="0.10"}

